name: CI
on: ["pull_request"]
env:
  GO111MODULE: on

jobs:
  build:
    name: Build, Test & Analyse
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Format using gofmt
        run: go fmt ./...

      - name: Run static analysis using vet
        run: go vet ./...

      - name: Compile code
        run: go build ./...

      - name: Run all tests with coverage
        run: go test -v -covermode=count -coverprofile=coverage.out ./...

      - name: Send coverage to Coveralls
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get -u github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=github
